# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master,main ]
  pull_request:
    branches: [ master,main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  docker:
    name: docker build-push-registry
    runs-on: ubuntu-latest
    steps:
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        run: |
          docker build -t sirpm/maven-web-app:GITHUB_SHA .
        
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        run: |
          docker push sirpm/maven-web-app:$GITHUB_SHA
 
